### ISSUE TITLE
Updates needed for recent Imgui examples changes?

### ISSUE THREAD

**Issue by meshula** [pthom/implot_demo#1]
Thanks for making this sample!

Does it need updating to match recent changes in ImGui? Pulled and built via the emscripten script, and got this:

````
implot_demo/external/hello_imgui/src/hello_imgui/internal/backend_impls/runner_sdl_opengl3.cpp:6:10: fatal error: 'examples/imgui_impl_opengl3.h' file not found
#include <examples/imgui_impl_opengl3.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by pthom** [comment]
Sorry, your message went unnoticed on my side for a while. You were right, it needed updating.

I just pushed a commit that updates the dependencies (imgui, implot, and hello_imgui).
It should now work (but you might need to clear your previous build directory).

I'm closing this issue for now, feel free to open another one if you encounter another issue.
